###############################################################################
# MASTERNODE AUTOINSTALLER by Lyndros <lyndros@hotmail.com>                   #
###############################################################################
# Repository: https://github.com/Lyndros/crypto_tools                         #
#                                                                             #
# If you want to support and motivate me I accept donations even 1 TOK is     #
# always welcome :-)!                                                         #
# > ethereum address: 0x44F102616C8e19fF3FED10c0b05B3d23595211ce              #
# > tokugawa address: TjrQBaaCPoVW9mPAZHPfVx9JJCq7yZ7QnA                      #
#                                                                             #
###############################################################################

###############################################################################
#                     Configuration for Ubuntu 18.04                          #
###############################################################################

###############################################################################
#            USUALLY THESE SETTINGS DOES NOT NEED TO BE MODIFIED              #
###############################################################################
#GENERAL OS SETTINGS
system:   Ubuntu 18.04

preparation:
        - /usr/bin/apt-get install -y build-essential libtool autotools-dev pkg-config libssl-dev libboost-all-dev autoconf automake
        - /usr/bin/apt-get install -y libqt4-dev libminiupnpc-dev
        - /usr/bin/apt-get install -y libgmp-dev
        - /usr/bin/apt-get install -y openssl
        - /usr/bin/apt-get install -y apt-get install software-properties-common && add-apt-repository ppa:bitcoin/bitcoin
        - /usr/bin/apt-get update  -y
        - /usr/bin/apt-get install -y libdb4.8-dev libdb4.8++-dev
        - /usr/bin/apt-get install -y ufw

firewall_profiles: /etc/ufw/aplications.d/

###############################################################################
#         MASTERNODE CONFIGURATION                                            #
#         Define your IP, port and private keys                               #
#         NOTE: Use the same ip address if sharing same VPS for all MNs       #
###############################################################################
coinname: Tokugawa
services: enabled
test:     enabled                                 #PACKAGES ARE NOT INSTALLED

MASTERNODES:
      - name:             MN01
        rpcport:          21116          
        ip:               $IP_ADDR_MN01$          #IP FOR MN01
        ports:
          - 21117                                 #EXTERNAL PORT FOR MN01
        protocols:
          - tcp
        privkey:          $MN01_PRIVKEY$

      - name:             MN02
        rpcport:          21118
        ip:               $IP_ADDR_MN02$          #IP FOR MN02 can be equal to MN01
        ports:
          - 21119                                #EXTERNAL PORT FOR MN02
        protocols:
          - tcp
        privkey:          $MN02_PRIVKEY$
